name: CI/CD - Build S1 and Deploy via App Repo

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout source repo (s1)
        uses: actions/checkout@v4

      - name: Build Go app
        run: go build -o app main.go

      - name: Build Docker image
        run: docker build -t k-cicd-s1:latest .

      - name: Save Docker image to file
        run: docker save k-cicd-s1:latest -o s1.tar

      - name: Import image into k3s
        run: |
          sudo k3s ctr images import s1.tar
          rm s1.tar

      - name: Clone k-cicd-app repo
        run: |
          git clone https://github.com/init-vlad/k-cicd-app.git
          kubectl apply -k k-cicd-app -n env-server
          rm -rf k-cicd-app

